# TO CREATE: ansible-playbook -i localhost,   -e '{"instances":["mongodb","catalogue","redis","user","cart","mysql","shipping","rabbitmq","payment","frontend"]}' roboshop.yaml
# TO DELETE: ansible-playbook -i localhost,   -e '{"instances":["mongodb","catalogue","redis","user","cart","mysql","shipping","rabbitmq","payment","frontend"]}'  -e action=destroy roboshop.yaml
# or
# ansible-playbook -i localhost, -e " instances = [ 'mongodb', 'catalogue', 'redis']" roboshop.yaml
# ansible-playbook -i localhost, -e " instances = [ 'mongodb', 'catalogue', 'redis']" -e action=destroy roboshop.yaml
- name: create ec2 and r53 records
  hosts: all
  connection: local
  vars:
    sg_id: sg-084d04e99c224c7bc
    ami_id: ami-0220d79f3f480ecf5
    domain_name: vadla.online
    env: dev
    action: create
    instances:
    - mongodb
    - catalogue
  tasks:
  ### CREATE ###
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      name: "{{ item }}-{{ env }}"
      tags:
        Project: roboshop
        Component: "{{ item }}"
        Environment: "{{ env }}"
        Name: "{{ item }}-{{ env }}"
    loop: "{{ instances }}"
    register: ec2_output
    when: action == "create"

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"
    when: action == "create"

  - name: create r53 records
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item }}-{{ env }}.{{ domain_name }}" # mongodb-dev.daws88s.online, frontend-dev.daws88s.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true # we can give wait: false then it won't wait until DNS get reflected
    loop: "{{ ec2_output.results }}"
    when: action == "create"

  - name: create r53 records
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "roboshop-{{ env }}.{{ domain_name }}" # roboshop-dev.daws88s.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true # we can give wait: false then it won't wait until DNS get reflected
    loop: "{{ ec2_output.results }}"
    when:  # and
    - item.item == "frontend"
    - action == "create"

  ### DESTROY ###
  - name: delete r53 records
    amazon.aws.route53:
      state: absent
      zone: "{{ domain_name }}"
      record: "{{ item }}-{{ env }}.{{ domain_name }}" # roboshop-dev.daws88s.online
      type: A
      ttl: 1
    loop: "{{ instances }}"
    when: action == "destroy"

  - name: delete ec2 instance
    amazon.aws.ec2_instance:
      state: absent
      name: "{{ item }}-{{ env }}"
    loop: "{{ instances }}"
    when: action == "destroy"